"""PostgreSQL persistence adapter for inspections, jobs and the outbox."""

from .analytics_contracts import (
    DownloadAnalyticsDailySnapshot,
    DownloadAnalyticsSnapshot,
    DownloadAnalyticsSourceSnapshot,
    DownloadAnalyticsSummarySnapshot,
)
from .base import Base
from .completion_repository import build_artifact_object_key
from .contracts import (
    ArtifactCreate,
    ArtifactPurgeResult,
    ArtifactSnapshot,
    DownloadCreate,
    DownloadHistoryItemSnapshot,
    DownloadHistoryPageSnapshot,
    DownloadHistorySummarySnapshot,
    FormatCreate,
    FormatSnapshot,
    InspectionCreate,
    InspectionCreateResult,
    InspectionSnapshot,
    JobCreateResult,
    JobSnapshot,
    JobSourceSnapshot,
    OutboxSnapshot,
    RetrySourceSnapshot,
)
from .errors import (
    IdempotencyConflict,
    LeaseConflict,
    RepositoryConflict,
    RepositoryError,
    RepositoryNotFound,
)
from .models import (
    AnalysisArtifactLockRow,
    AnalysisJobRow,
    AnalysisReportArtifactRow,
    AnalysisReportVersionRow,
    AnalysisResultRow,
    ArtifactRow,
    AuthSessionRow,
    DownloadJobRow,
    MediaFormatRow,
    MediaInspectionRow,
    OutboxEventRow,
    ProviderCanaryResultRow,
    TaskEventRow,
    UserRow,
)
from .outbox_repository import SqlAlchemyDownloadRepository
from .session import create_engine, create_session_factory

__all__ = [
    "ArtifactCreate",
    "ArtifactPurgeResult",
    "ArtifactRow",
    "ArtifactSnapshot",
    "AuthSessionRow",
    "AnalysisArtifactLockRow",
    "AnalysisJobRow",
    "AnalysisReportArtifactRow",
    "AnalysisReportVersionRow",
    "AnalysisResultRow",
    "Base",
    "DownloadCreate",
    "DownloadAnalyticsDailySnapshot",
    "DownloadAnalyticsSnapshot",
    "DownloadAnalyticsSourceSnapshot",
    "DownloadAnalyticsSummarySnapshot",
    "DownloadHistoryItemSnapshot",
    "DownloadHistoryPageSnapshot",
    "DownloadHistorySummarySnapshot",
    "DownloadJobRow",
    "FormatCreate",
    "FormatSnapshot",
    "IdempotencyConflict",
    "InspectionCreate",
    "InspectionCreateResult",
    "InspectionSnapshot",
    "JobCreateResult",
    "JobSnapshot",
    "JobSourceSnapshot",
    "LeaseConflict",
    "MediaFormatRow",
    "MediaInspectionRow",
    "OutboxEventRow",
    "ProviderCanaryResultRow",
    "TaskEventRow",
    "OutboxSnapshot",
    "RepositoryConflict",
    "RepositoryError",
    "RepositoryNotFound",
    "RetrySourceSnapshot",
    "SqlAlchemyDownloadRepository",
    "UserRow",
    "build_artifact_object_key",
    "create_engine",
    "create_session_factory",
]
