x-include-prod-env: &video-prod-env
  env_file: .env.prod

services:
  api:
    <<: *video-prod-env

  outbox:
    <<: *video-prod-env

  worker-download:
    <<: *video-prod-env

  worker-analysis:
    <<: *video-prod-env

  media-runner:
    <<: *video-prod-env

  postgres:
    <<: *video-prod-env

  rabbitmq:
    <<: *video-prod-env

  minio:
    <<: *video-prod-env

  minio-init:
    <<: *video-prod-env
