// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"ant-design-pro-layout","id":"1"},"2":{"path":"/login","redirect":"/workspace","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"下载工作台","path":"/workspace","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"任务历史","path":"/tasks","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"*","redirect":"/","parentId":"ant-design-pro-layout","id":"5"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Workspace__index" */'@/pages/Workspace/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Tasks__index" */'@/pages/Tasks/index.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/stephenqiu/Desktop/StephenQiu30/Video/apps/web/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
