def video_report_labels(language: str) -> dict[str, str]:
    if language.lower().startswith("zh"):
        return {
            "report_title": "逐分镜导演拉片分析报告",
            "report_intro": (
                "本报告按照影视导演拉片方式进行整理，以可复核分析分镜为单位，"
                "区分实际剪辑边界与连续长镜头内的视觉节拍，重点分析时长、画面"
                "信息、景别、摄影语言、叙事作用、情绪价值及高光候选。"
            ),
            "basic_info": "一、基础信息",
            "analysis_method": "分析方式",
            "cut_analysis": "逐分镜（Cut + 连续节拍）分析",
            "shot_statistics": "分析分镜统计",
            "cut_statistics": (
                "按真实编辑边界或连续镜头内有证据的视觉节拍拆分，不按固定秒数切片。"
            ),
            "director_summary": "导演综述",
            "shot_number": "镜头编号",
            "timecode": "时间码",
            "shot_duration": "时长",
            "picture_content": "画面内容",
            "camera_language": "景别 / 运镜 / 边界",
            "narrative": "叙事作用",
            "highlight_level": "高光等级",
            "production_advice": "四、AI 制作建议",
            "priority_shots": "重点还原镜头",
            "recommended_extensions": "建议扩展",
            "subtitle": "AI 视频视觉分析报告",
            "overview": "报告概览",
            "language": "输出语言",
            "duration": "视频时长",
            "format": "文件格式",
            "size": "文件大小",
            "shots": "分镜数量",
            "summary": "视觉摘要",
            "shot_list": "分镜分析",
            "shot_size": "景别",
            "camera": "镜头运动",
            "transition": "转场",
            "tags": "视觉标签",
            "none": "无",
            "scenes": "二、场景提炼",
            "scene": "场景",
            "location": "空间",
            "visual_rules": "视觉规则",
            "continuity_risks": "连续性风险",
            "no_continuity_risks": "未发现明确连续性风险。",
            "highlights": "三、高光镜头分析",
            "no_highlights": "未识别出独立视觉高光。",
            "time": "时间范围",
            "reason": "入选理由",
            "assets": "五、视觉资产目录",
            "no_assets": "未识别出可复用的视觉资产。",
            "type": "类型",
            "label": "名称",
            "first_seen": "首次出现",
        }
    return {
        "report_title": "Visual-segment director breakdown",
        "report_intro": (
            "This report uses reviewable visual segments, distinguishing physical "
            "edits from meaningful beats inside continuous takes, to examine duration, "
            "visual content, framing, camera language, narrative function, and "
            "highlights."
        ),
        "basic_info": "1. Basic information",
        "analysis_method": "Analysis method",
        "cut_analysis": "Visual segments (cuts + continuous beats)",
        "shot_statistics": "Analysis segment count",
        "cut_statistics": (
            "Split on verified edits or meaningful beats inside continuous takes, "
            "never by a fixed time grid."
        ),
        "director_summary": "Director summary",
        "shot_number": "Shot",
        "timecode": "Timecode",
        "shot_duration": "Duration",
        "picture_content": "Visual content",
        "camera_language": "Framing / motion / boundary",
        "narrative": "Narrative function",
        "highlight_level": "Highlight level",
        "production_advice": "4. AI production advice",
        "priority_shots": "Priority shots",
        "recommended_extensions": "Recommended extensions",
        "subtitle": "AI visual analysis report",
        "overview": "Report overview",
        "language": "Output language",
        "duration": "Duration",
        "format": "Format",
        "size": "File size",
        "shots": "Shot count",
        "summary": "Visual summary",
        "shot_list": "Shot analysis",
        "shot_size": "Shot size",
        "camera": "Camera motion",
        "transition": "Transition",
        "tags": "Visual tags",
        "none": "None",
        "scenes": "2. Scene extraction",
        "scene": "Scene",
        "location": "Location",
        "visual_rules": "Visual rules",
        "continuity_risks": "Continuity risks",
        "no_continuity_risks": "No explicit continuity risks were identified.",
        "highlights": "3. Highlight shot analysis",
        "no_highlights": "No distinct visual highlights were identified.",
        "time": "Time range",
        "reason": "Selection reason",
        "assets": "5. Visual asset catalog",
        "no_assets": "No reusable visual assets were identified.",
        "type": "Type",
        "label": "Label",
        "first_seen": "First seen",
    }
